### ISSUE TITLE
Problem when overwriting existing file in Recorder option

### ISSUE THREAD

**Issue by MichaelMausbach** [MichaelMausbach/TrafficDetection#8]
When a file is available, user is asked if it can be overwritten.
After this, I receive an errror:

```
  File "C:/Data/Git/Tools/TrafficDetection/Traffic_detection.py", line 119, in RecordVideo
    LiveFeed = imutils.resize(LiveFeed, width=conf["ResolutionW"], height=conf["ResolutionH"])
```

**Comment by MichaelMausbach** [comment]
```
File exists! Overwrite? (y/n) :>? y
[INFO]          - File deleted: test.avi
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Data/Git/Tools/TrafficDetection/Traffic_detection.py", line 346, in <module>
    RecordVideo(camera)
  File "C:/Data/Git/Tools/TrafficDetection/Traffic_detection.py", line 110, in RecordVideo
    RecordVideo(camera)                                                                                         # restart function and re-ask for the name
  File "C:/Data/Git/Tools/TrafficDetection/Traffic_detection.py", line 119, in RecordVideo
    LiveFeed = imutils.resize(LiveFeed, width=conf["ResolutionW"], height=conf["ResolutionH"])
  File "C:\Data\Python Virtual Environments\TrafficDetection\lib\site-packages\imutils\convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
```
